=== r-forge/timpgui/Glotaran/JAXBWizzardOutput/xml-resources/jaxb/TgmBinding/TgmSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.nat.vu.nl/~jsnel/Schema/TgmSchema"
            xmlns:tns="http://www.nat.vu.nl/~jsnel/Schema/TgmSchema"
            elementFormDefault="qualified" version="0.1" id="TgmSchema">
    <xsd:complexType name="Dat">
        <xsd:sequence>
            <xsd:element name="kinparPanel" type="tns:KinparPanelModel" nillable="true"></xsd:element>
            <xsd:element name="modelName" type="xsd:string" default="SpecifyModelName" nillable="true"></xsd:element>
            <xsd:element name="modType" type="xsd:string" default="kin" nillable="true"></xsd:element>
            <xsd:element name="irfparPanel" type="tns:IrfparPanelModel" nillable="true"></xsd:element>
            <xsd:element name="cohspecPanel" type="tns:CohspecPanelModel" nillable="true"></xsd:element>
            <xsd:element name="kMatrixPanel" type="tns:KMatrixPanelModel" nillable="true"/>
            <xsd:element name="weightParPanel" type="tns:WeightParPanelModel" nillable="true"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="KinparPanelModel">
        <xsd:sequence>
            <xsd:element name="positivepar" type="xsd:boolean" default="false"/>
            <xsd:element name="kinpar" type="tns:KinPar" maxOccurs="unbounded" nillable="true"></xsd:element>
            <xsd:element name="seqmod" type="xsd:boolean" default="false"/>

        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="KinPar">
        <xsd:sequence>
            <xsd:element name="start" type="xsd:double"></xsd:element>
            <xsd:element name="fixed" type="xsd:boolean" default="false" nillable="true"></xsd:element>
            <xsd:element name="constrained" type="xsd:boolean" default="false" nillable="true"></xsd:element>
            <xsd:sequence>
                <xsd:element name="max" type="xsd:double"></xsd:element>
                <xsd:element name="min" type="xsd:double"></xsd:element>
            </xsd:sequence>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="tgm">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="dat" type="tns:Dat" nillable="true"></xsd:element>
                <xsd:element name="panelStates" type="xsd:boolean" nillable="true" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:complexType name="IrfparPanelModel">
        <xsd:sequence>
            <xsd:element name="dispmufun" type="xsd:string" nillable="true"></xsd:element>
            <xsd:element name="disptaufun" type="xsd:string" nillable="true"></xsd:element>
            <xsd:element name="parmu" type="xsd:string" nillable="true"></xsd:element>
            <xsd:element name="partau" type="xsd:string" nillable="true"></xsd:element>
            <xsd:element name="parmufixed" type="xsd:boolean" default="false" nillable="true"></xsd:element>
            <xsd:element name="partaufixed" type="xsd:boolean" default="false" nillable="true"></xsd:element>
            <xsd:element name="lamda" type="xsd:double" nillable="true"></xsd:element>
            <xsd:element name="irf" type="xsd:double" maxOccurs="unbounded" default="0" nillable="true"></xsd:element>
            <xsd:element name="fixed" type="xsd:boolean" default="false" maxOccurs="unbounded" nillable="true"/>
            <xsd:element name="backsweepEnabled" type="xsd:boolean" nillable="true" default="false"/>
            <xsd:element name="backsweepPeriod" type="xsd:double" nillable="true"/>
            <xsd:element name="measuredIrf" nillable="true" maxOccurs="1" type="xsd:string"/>
            <xsd:element name="mirf" type="xsd:boolean" default="false" nillable="true"></xsd:element>
            <xsd:element name="convalg" type="xsd:int" default="2" nillable="true"></xsd:element>
            <xsd:element name="reftau" type="xsd:double" nillable="true"></xsd:element>

        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="CohspecPanelModel">
        <xsd:sequence>
            <xsd:element name="cohspec" type="tns:Cohspec" nillable="true"></xsd:element>
            <xsd:element name="coh" type="xsd:string" maxOccurs="1" nillable="true"></xsd:element>
            <xsd:element name="clp0Enabled" type="xsd:boolean" nillable="true" minOccurs="1"/>
            <xsd:element name="clp0Min" nillable="true" minOccurs="1" type="xsd:double"/>
            <xsd:element name="clp0Max" minOccurs="1" nillable="true" type="xsd:double"/>

        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="Cohspec">
        <xsd:sequence>
            <xsd:element name="type" type="xsd:string"></xsd:element>
            <xsd:element name="set" type="xsd:boolean" default="false"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="KMatrixPanelModel">
        <xsd:sequence>
            <xsd:element name="kMatrix" type="tns:IntMatrix"/>
            <xsd:element name="relationsMatrix" type="tns:Double2BoolMatrix" nillable="true"/>
            <xsd:element name="jVector" type="tns:JVector" maxOccurs="1" minOccurs="1" nillable="true"/>
            <xsd:element name="spectralContraints" type="tns:SpectralConstraints" nillable="true"/>
            <xsd:element name="contrainsMatrix" type="tns:Double2Matrix" nillable="true"/>
            <xsd:element name="KinScal" type="tns:KinPar" maxOccurs="unbounded" nillable="true"/>

        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="IntMatrix">
        <xsd:sequence>
            <xsd:element name="data" maxOccurs="unbounded" minOccurs="1" nillable="true">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="row" type="xsd:int" maxOccurs="unbounded" minOccurs="1"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="WeightParPanelModel">
        <xsd:sequence>
            <xsd:element name="weightpar" minOccurs="0" maxOccurs="unbounded" type="tns:WeightPar" nillable="true"/>

        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="WeightPar">
        <xsd:sequence>
            <xsd:element name="min1" type="xsd:double" minOccurs="1" nillable="true"/>
            <xsd:element name="min2" type="xsd:double" minOccurs="1" nillable="true"/>
            <xsd:element name="max1" type="xsd:double" minOccurs="1" nillable="true"/>
            <xsd:element name="max2" type="xsd:double" minOccurs="1" nillable="true"/>
            <xsd:element name="weight" type="xsd:double" minOccurs="1" nillable="true"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="JVector">
        <xsd:sequence>
            <xsd:element name="vector" maxOccurs="unbounded" nillable="true" type="xsd:double"/>
            <xsd:element name="fixed" type="xsd:boolean" maxOccurs="unbounded" nillable="true"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="SpectralConstraints">
        <xsd:sequence>
            <xsd:element name="min" maxOccurs="unbounded" nillable="true" type="xsd:double"/>
            <xsd:element name="max" type="xsd:double" maxOccurs="unbounded" nillable="true"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="Double2Matrix">
        <xsd:sequence>
            <xsd:element name="data" maxOccurs="unbounded" nillable="true">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="min" type="xsd:double" nillable="true" maxOccurs="unbounded"/>
                        <xsd:element name="max" type="xsd:double" maxOccurs="unbounded" nillable="true"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="Double2BoolMatrix">
        <xsd:sequence>
            <xsd:element name="data" maxOccurs="unbounded" nillable="true">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="c0" type="xsd:double" maxOccurs="unbounded" nillable="true"/>
                        <xsd:element name="c1" maxOccurs="unbounded" type="xsd:double"/>
                        <xsd:element name="c0fixed" maxOccurs="unbounded" type="xsd:boolean" nillable="true"/>
                        <xsd:element name="c1fixed" type="xsd:boolean" maxOccurs="unbounded" nillable="true"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== r-forge/timpgui/MPUR/TgmProjectSupport/templates/SampleTgmProject/models/SampleModel.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : TgmSchema.xml
    Created on : October 1, 2009, 10:09 AM
    Author     : jsg210
    Description:
        Purpose of the document follows.
-->

<ns0:tgm  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns0='http://www.nat.vu.nl/~jsnel/Schema/TgmSchema'
   xsi:schemaLocation='http://www.nat.vu.nl/~jsnel/Schema/TgmSchema TgmSchema.xsd'>
    <ns0:dat>
        <ns0:kinparPanel>
            <ns0:positivepar>false</ns0:positivepar>
            <ns0:kinpar>
                <ns0:start>NaN</ns0:start>
                <ns0:fixed>false</ns0:fixed>
                <ns0:constrained>false</ns0:constrained>
                <ns0:max>NaN</ns0:max>
                <ns0:min>NaN</ns0:min>
            </ns0:kinpar>
            <ns0:kinpar>
                <ns0:start>NaN</ns0:start>
                <ns0:fixed>false</ns0:fixed>
                <ns0:constrained>false</ns0:constrained>
                <ns0:max>NaN</ns0:max>
                <ns0:min>NaN</ns0:min>
            </ns0:kinpar>
            <ns0:kinpar>
                <ns0:start>NaN</ns0:start>
                <ns0:fixed>false</ns0:fixed>
                <ns0:constrained>false</ns0:constrained>
                <ns0:max>NaN</ns0:max>
                <ns0:min>NaN</ns0:min>
            </ns0:kinpar>
            <ns0:seqmod>false</ns0:seqmod>
        </ns0:kinparPanel>
        <ns0:modelName>SpecifyModelName</ns0:modelName>
        <ns0:modType>kin</ns0:modType>
        <ns0:irfparPanel>
            <ns0:dispmufun></ns0:dispmufun>
            <ns0:disptaufun></ns0:disptaufun>
            <ns0:parmu></ns0:parmu>
            <ns0:partau></ns0:partau>
            <ns0:dispmu>false</ns0:dispmu>
            <ns0:disptau>false</ns0:disptau>
            <ns0:lamda>NaN</ns0:lamda>
            <ns0:irf>0</ns0:irf>
            <ns0:irf>0</ns0:irf>
            <ns0:irf>0</ns0:irf>
            <ns0:fixed>false</ns0:fixed>
            <ns0:fixed>false</ns0:fixed>
            <ns0:fixed>false</ns0:fixed>
            <ns0:backsweepEnabled>false</ns0:backsweepEnabled>
            <ns0:backsweepPeriod></ns0:backsweepPeriod>
        </ns0:irfparPanel>
        <ns0:cohspecPanel>
            <ns0:cohspec>
                <ns0:type></ns0:type>
                <ns0:set>false</ns0:set>
            </ns0:cohspec>
            <ns0:coh></ns0:coh>
            <ns0:clp0Enabled></ns0:clp0Enabled>
            <ns0:clp0Min></ns0:clp0Min>
            <ns0:clp0Max></ns0:clp0Max>
        </ns0:cohspecPanel>
        <ns0:flimPanel>
            <ns0:mirf>false</ns0:mirf>
            <ns0:convalg>2</ns0:convalg>
            <ns0:reftau>NaN</ns0:reftau>
        </ns0:flimPanel>
        <ns0:kMatrixPanel>
            <ns0:kMatrix>
                <ns0:data>
                    <ns0:row></ns0:row>
                    <ns0:row></ns0:row>
                    <ns0:row></ns0:row>
                </ns0:data>
                <ns0:data>
                    <ns0:row></ns0:row>
                    <ns0:row></ns0:row>
                    <ns0:row></ns0:row>
                </ns0:data>
                <ns0:data>
                    <ns0:row></ns0:row>
                    <ns0:row></ns0:row>
                    <ns0:row></ns0:row>
                </ns0:data>
            </ns0:kMatrix>
            <ns0:relationsMatrix>
                <ns0:data>
                    <ns0:c0></ns0:c0>
                    <ns0:c0></ns0:c0>
                    <ns0:c0></ns0:c0>
                    <ns0:c1></ns0:c1>
                    <ns0:c1></ns0:c1>
                    <ns0:c1></ns0:c1>
                    <ns0:c0fixed></ns0:c0fixed>
                    <ns0:c0fixed></ns0:c0fixed>
                    <ns0:c0fixed></ns0:c0fixed>
                    <ns0:c1fixed></ns0:c1fixed>
                    <ns0:c1fixed></ns0:c1fixed>
                    <ns0:c1fixed></ns0:c1fixed>
                </ns0:data>
            </ns0:relationsMatrix>
            <ns0:jVector>
                <ns0:vector></ns0:vector>
                <ns0:vector></ns0:vector>
                <ns0:vector></ns0:vector>
                <ns0:fixed></ns0:fixed>
                <ns0:fixed></ns0:fixed>
                <ns0:fixed></ns0:fixed>
            </ns0:jVector>
            <ns0:spectralContraints>
                <ns0:min></ns0:min>
                <ns0:min></ns0:min>
                <ns0:min></ns0:min>
                <ns0:max></ns0:max>
                <ns0:max></ns0:max>
                <ns0:max></ns0:max>
            </ns0:spectralContraints>
            <ns0:contrainsMatrix>
                <ns0:data>
                    <ns0:min></ns0:min>
                    <ns0:min></ns0:min>
                    <ns0:min></ns0:min>
                    <ns0:max></ns0:max>
                    <ns0:max></ns0:max>
                    <ns0:max></ns0:max>
                </ns0:data>
            </ns0:contrainsMatrix>
        </ns0:kMatrixPanel>
        <ns0:weightParPanel>
            <ns0:weightpar>
                <ns0:min1>NaN</ns0:min1>
                <ns0:min2>NaN</ns0:min2>
                <ns0:max1>NaN</ns0:max1>
                <ns0:max2>NaN</ns0:max2>
                <ns0:weight>NaN</ns0:weight>
            </ns0:weightpar>
            <ns0:weightpar>
                <ns0:min1>NaN</ns0:min1>
                <ns0:min2>NaN</ns0:min2>
                <ns0:max1>NaN</ns0:max1>
                <ns0:max2>NaN</ns0:max2>
                <ns0:weight>NaN</ns0:weight>
            </ns0:weightpar>
            <ns0:weightpar>
                <ns0:min1>NaN</ns0:min1>
                <ns0:min2>NaN</ns0:min2>
                <ns0:max1>NaN</ns0:max1>
                <ns0:max2>NaN</ns0:max2>
                <ns0:weight>NaN</ns0:weight>
            </ns0:weightpar>
        </ns0:weightParPanel>
    </ns0:dat>

</ns0:tgm>

=== r-forge/timpgui/Glotaran/JAXBWizzardOutput/src/org/glotaran/core/models/tgm/TgmSchema1.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : TgmSchema1.xml
    Created on : March 3, 2010, 9:24 AM
    Author     : jsg210
    Description:
        Purpose of the document follows.
-->

<ns0:tgm  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns0='http://www.nat.vu.nl/~jsnel/Schema/TgmSchema'
   xsi:schemaLocation='http://www.nat.vu.nl/~jsnel/Schema/TgmSchema TgmSchema.xsd'>
    <ns0:dat>
        <ns0:kinparPanel>
            <ns0:positivepar>false</ns0:positivepar>
            <ns0:seqmod>false</ns0:seqmod>
        </ns0:kinparPanel>
        <ns0:modelName>SpecifyModelName</ns0:modelName>
        <ns0:modType>kin</ns0:modType>
        <ns0:irfparPanel>
            <ns0:dispmufun></ns0:dispmufun>
            <ns0:disptaufun></ns0:disptaufun>
            <ns0:parmu></ns0:parmu>
            <ns0:partau></ns0:partau>
            <ns0:parmufixed>false</ns0:parmufixed>
            <ns0:partaufixed>false</ns0:partaufixed>
            <ns0:lamda></ns0:lamda>
            <ns0:backsweepEnabled>false</ns0:backsweepEnabled>
            <ns0:backsweepPeriod></ns0:backsweepPeriod>
            <ns0:measuredIrf></ns0:measuredIrf>
            <ns0:mirf>false</ns0:mirf>
            <ns0:convalg>2</ns0:convalg>
            <ns0:reftau></ns0:reftau>
        </ns0:irfparPanel>
        <ns0:cohspecPanel>
            <ns0:cohspec>
                <ns0:type></ns0:type>
                <ns0:set>false</ns0:set>
            </ns0:cohspec>
            <ns0:coh></ns0:coh>
            <ns0:clp0Enabled></ns0:clp0Enabled>
            <ns0:clp0Min></ns0:clp0Min>
            <ns0:clp0Max></ns0:clp0Max>
        </ns0:cohspecPanel>
        <ns0:kMatrixPanel>
            <ns0:kMatrix>
            </ns0:kMatrix>
            <ns0:relationsMatrix>
            </ns0:relationsMatrix>
            <ns0:jVector>
            </ns0:jVector>
            <ns0:spectralContraints>
            </ns0:spectralContraints>
            <ns0:contrainsMatrix>
            </ns0:contrainsMatrix>
        </ns0:kMatrixPanel>
        <ns0:weightParPanel>
        </ns0:weightParPanel>
    </ns0:dat>

</ns0:tgm>

=== r-forge/timpgui/MPUR/TgmProjectSupport/templates/EmptyTgmProject/models/EmptyTgmFile.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : TgmSchema.xml
    Created on : September 18, 2009, 11:33 AM
    Author     : jsg210
    Description:
        Purpose of the document follows.
-->

<ns0:tgm  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns0='http://www.nat.vu.nl/~jsnel/Schema/TgmSchema'
   xsi:schemaLocation='http://www.nat.vu.nl/~jsnel/Schema/TgmSchema TgmSchema.xsd'>
    <ns0:dat>
        <ns0:kinparPanel>
            <ns0:positivepar>false</ns0:positivepar>
            <ns0:seqmod>false</ns0:seqmod>
        </ns0:kinparPanel>
        <ns0:modelName>SpecifyModelName</ns0:modelName>
        <ns0:modType>kin</ns0:modType>
        <ns0:irfparPanel>
            <ns0:dispmufun></ns0:dispmufun>
            <ns0:disptaufun></ns0:disptaufun>
            <ns0:parmu></ns0:parmu>
            <ns0:partau></ns0:partau>
            <ns0:dispmu>false</ns0:dispmu>
            <ns0:disptau>false</ns0:disptau>
            <ns0:lamda>NaN</ns0:lamda>
        </ns0:irfparPanel>
        <ns0:cohspecPanel>
            <ns0:cohspec>
                <ns0:type></ns0:type>
                <ns0:set>false</ns0:set>
            </ns0:cohspec>
            <ns0:coh></ns0:coh>
        </ns0:cohspecPanel>
        <ns0:flimPanel>
            <ns0:mirf>false</ns0:mirf>
            <ns0:convalg>2</ns0:convalg>
            <ns0:reftau>NaN</ns0:reftau>
        </ns0:flimPanel>
        <ns0:kMatrixPanel>
            <ns0:k1matrix>
            </ns0:k1matrix>
            <ns0:k2matrix>
            </ns0:k2matrix>
        </ns0:kMatrixPanel>
    </ns0:dat>

</ns0:tgm>
